udpate to show ssh connections

diff --git a/operations/utils/sysadmin/subtu_show_ssh_connections b/operations/utils/sysadmin/subtu_show_ssh_connections
--- a/operations/utils/sysadmin/subtu_show_ssh_connections
+++ b/operations/utils/sysadmin/subtu_show_ssh_connections
@@ -18,11 +18,63 @@ if chk_flag --help $@ || chk_flag help $@; then
   exit_success
 fi
 
-# check for valid user inputs
-if ! chk_flag -h $@ && ! chk_flag -t $@ ; then
-  error "Missing host -h <arg> and window title -t <title> flags."
-  exit_failure
-fi
+# globals params
+GL_SSH_CONFIG="$HOME/.ssh/config"
+
+# check for an open ssh connection
+function check_open_ssh_connection() {
+  connection=$1
+  if ssh -q -o BatchMode=yes -o ConnectTimeout=1 $connection exit 2>/dev/null; then
+    printf "${FG_LCYAN} %30s %13s ${FG_DEFAULT} \n" "$connection" "OK."
+  else
+    printf "${FG_RED} %30s %13s ${FG_DEFAULT} \n" "$connection" "FAIL"
+  fi
+}
+
+# display open ssh connections
+function display() {
+  cfile=$1
+  # case insensitive match
+  shopt -s nocasematch
+  matched=false
+  for str in $(grep -i "^[^#\S]*Host\(name\)\?" $cfile | paste -s -); do
+    # check for connection
+    if [ "$matched" = true ]; then
+      check_open_ssh_connection "$str"
+      matched=false
+    fi
+    # ssh connection string is after the'Host' matched tag
+    [ "$str" = "Host" ] && matched=true;
+  done
+}
+
+# traverse all ssh configuration files
+function traverse() {
+  cfile=$1
+  text "$cfile \n"
+
+  # base case, display for this configuration
+  display $cfile
+
+  # traverse all the included ssh configuration files
+  matched=false
+  for str in $(grep -i "^[^#\S]*Include\?" $cfile | paste -s -); do
+    # traverse the include directory
+    if [ "$matched" = true ]; then
+      # get the ssh config file, directory path
+      cdir="$(dirname $cfile)/$str"
+      cdir=$(echo "$cdir" | sed 's/[*]\+//g')
+      for next_cfile in $cdir/*; do
+        newline
+        traverse $next_cfile
+      done
+      matched=false
+    fi
+
+    # included ssh configuration file is after 'Include' matched tag
+    [ "$str" == "Include" ] && matched=true;
+  done
+}
 
 # //////////////////////////////////////////////////////////////////////////////
 # @brief: script main entrypoint
@@ -33,35 +85,11 @@ title "Show SSH Connections\n"
 __dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
 pushd $__dir
 
+# trap ctrl-c and call ctrl_c
+trap ctrl_c INT
+
 # check every connection in the user's ssh config
-shopt -s nocasematch
-for str in $(grep -i "^[^#\S]*Host\(name\)\?" ~/.ssh/config | paste -s -); do
-  case "$str" in
-    "Host")
-      type=connection
-      ;;
-    "Hostname")
-      type=hostname
-      ;;
-    *)
-      case "$type" in
-        # get the name of the connection & test out an ssh connection
-        "connection")
-          connection=$str
-          if ssh -q -o BatchMode=yes -o ConnectTimeout=1 $connection exit 2>/dev/null; then
-            printf "${GREEN}"
-            printf "%30s %13s" "$connection" "OK."
-            printf "\n${NC}"
-          else
-            printf "${RED}"
-            printf "%30s %13s" "$connection" "FAIL"
-            printf "\n${NC}"
-          fi
-          unset connection
-        ;;
-      esac
-  esac
-done
+traverse $GL_SSH_CONFIG
 
 # cleanup & exit
 exit_on_success
